### ISSUE TITLE
Feature Request - Local Playlists

### ISSUE THREAD

**Issue by 8o8inCodes** [maplestory-music/maplestory-music.github.io#12]
Fantastic day to you!

Would be nice to be able to create local playlists (that are saved in browser's storage), with the tracks that people like.

Problem is that I hit the shuffle button, it starts playing, but sometimes there are tracks that I don't like, and don't want it to ever play it again. So I would love a button "Remove from playlist". If playlist doesn't exist yet, then it should probably ask "In order to do that, you need to create a playlist" with the playlist name prompt.

Would be truly perfect.

**Comment by nanochromatic** [comment]
If you filter the grid through the search bar or any of the column filters, the shuffle button is restricted to the contents of the filtered grid. For instance, if you only want to play tracks between 2003 and 2010, you would add a range filter to the Date column and the grid would be filtered. Although this isn't as flexible as a true playlist where you have full control of the contents, this might resolve some of your issues with filtering out tracks you want to skip.

The local playlist feature is something that I'd like to explore. However, because this is a static site and settings are not persisted on a server or across devices/browsers, user generated playlists are not very portable and prone to data loss if the cache is cleared.

**Comment by 8o8inCodes** [comment]
@nanochromatic Ah I understood, I wish github allowed local browser persistence/cache.
Thanks anyway

**Comment by nanochromatic** [comment]
This is technically possible with the current setup through localStorage, just that the "prone to data loss" aspect of it is quite daunting if it actually happens. Someone could conceivably spend hours creating playlists and accidentally lose all of it if their browser's cache gets wiped. For this reason I'm a bit hesitant to fully support a feature like this unless there's a server involved to persist the playlists.

**Comment by 8o8inCodes** [comment]
@nanochromatic Yeah you're right, could be problematic...
